services:
  book_flow_writer_agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book_flow_writer_agent
    ports:
      - "3773:3773"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}


    env_file:
      - .env
    volumes:
      - ./book_flow_writer_agent:/app/book_flow_writer_agent
      - ./agent_config.json:/app/agent_config.json
    restart: unless-stopped
    networks:
      - book_flow_writer_agent-network


networks:
  book_flow_writer_agent-network:
    driver: bridge
